/*
 * Minimal wayland-server-core.h shim for AMS.
 *
 * Provides the ABI surface needed by wlroots and by code generated by
 * the AMS wayland-scanner. This is NOT a full libwayland-server.h - we
 * deliberately keep it small and grow it on demand.
 */

#ifndef AMS_WAYLAND_SERVER_CORE_H
#define AMS_WAYLAND_SERVER_CORE_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

struct wl_display;
struct wl_event_loop;
struct wl_event_source;
struct wl_client;
struct wl_resource;
struct wl_global;

typedef int (*wl_event_loop_fd_func_t)(int fd, uint32_t mask, void *data);

struct wl_message {
    const char *name;
    const char *signature;
    const struct wl_interface **types;
};

struct wl_interface {
    const char *name;
    int         version;
    int         method_count;
    const struct wl_message *methods;
    int         event_count;
    const struct wl_message *events;
};

struct wl_list {
    struct wl_list *prev;
    struct wl_list *next;
};

void wl_list_init(struct wl_list *list);
void wl_list_insert(struct wl_list *list, struct wl_list *elm);
void wl_list_remove(struct wl_list *elm);
int  wl_list_empty(const struct wl_list *list);

#define WL_EVENT_READABLE 0x01
#define WL_EVENT_WRITABLE 0x02
#define WL_EVENT_HANGUP   0x04
#define WL_EVENT_ERROR    0x08

struct wl_display    *wl_display_create(void);
void                  wl_display_destroy(struct wl_display *display);
struct wl_event_loop *wl_display_get_event_loop(struct wl_display *display);
const char           *wl_display_add_socket_auto(struct wl_display *display);
int                   wl_display_add_socket(struct wl_display *display, const char *name);
void                  wl_display_run(struct wl_display *display);
void                  wl_display_terminate(struct wl_display *display);
void                  wl_display_flush_clients(struct wl_display *display);
uint32_t              wl_display_get_serial(struct wl_display *display);
uint32_t              wl_display_next_serial(struct wl_display *display);

struct wl_event_source *wl_event_loop_add_fd(struct wl_event_loop *loop,
                                             int fd, uint32_t mask,
                                             wl_event_loop_fd_func_t func, void *data);
int  wl_event_source_remove(struct wl_event_source *source);
int  wl_event_loop_dispatch(struct wl_event_loop *loop, int timeout);

struct wl_global *wl_global_create(struct wl_display *display,
                                   const struct wl_interface *iface,
                                   int version, void *data,
                                   void (*bind)(struct wl_client*, void*, uint32_t, uint32_t));
void              wl_global_destroy(struct wl_global *global);

struct wl_resource *wl_resource_create(struct wl_client *client,
                                       const struct wl_interface *iface,
                                       int version, uint32_t id);
void                wl_resource_destroy(struct wl_resource *resource);
uint32_t            wl_resource_get_id(struct wl_resource *resource);
struct wl_client   *wl_resource_get_client(struct wl_resource *resource);
void                wl_resource_set_implementation(struct wl_resource *resource,
                                                   const void *impl, void *data,
                                                   void (*destroy)(struct wl_resource*));
void                wl_resource_post_event(struct wl_resource *resource,
                                           uint32_t opcode, ...);
void                wl_resource_post_event_array(struct wl_resource *resource,
                                                 uint32_t opcode, void *args);

struct wl_client *wl_client_create(struct wl_display *display, int fd);
void              wl_client_destroy(struct wl_client *client);

#ifdef __cplusplus
}
#endif

#endif /* AMS_WAYLAND_SERVER_CORE_H */
