/* Słowa kluczowe C */
DEF_TOK(TOK_INT, "int")
DEF_TOK(TOK_VOID, "void")
DEF_TOK(TOK_CHAR, "char")
DEF_TOK(TOK_IF, "if")
DEF_TOK(TOK_ELSE, "else")
DEF_TOK(TOK_WHILE, "while")
DEF_TOK(TOK_DO, "do")
DEF_TOK(TOK_RETURN, "return")
DEF_TOK(TOK_FOR, "for")
DEF_TOK(TOK_BREAK, "break")
DEF_TOK(TOK_CONTINUE, "continue")
DEF_TOK(TOK_GOTO, "goto")
DEF_TOK(TOK_SWITCH, "switch")
DEF_TOK(TOK_CASE, "case")
DEF_TOK(TOK_DEFAULT, "default")
DEF_TOK(TOK_CONST1, "const")
DEF_TOK(TOK_CONST2, "__const") /* gcc extension */
DEF_TOK(TOK_CONST3, "__const__") /* gcc extension */
DEF_TOK(TOK_VOLATILE1, "volatile")
DEF_TOK(TOK_VOLATILE2, "__volatile") /* gcc extension */
DEF_TOK(TOK_VOLATILE3, "__volatile__") /* gcc extension */
DEF_TOK(TOK_LONG, "long")
DEF_TOK(TOK_REGISTER, "register")
DEF_TOK(TOK_SIGNED, "signed")
DEF_TOK(TOK_AUTO, "auto")
DEF_TOK(TOK_INLINE1, "inline")
DEF_TOK(TOK_INLINE2, "__inline") /* gcc extension */
DEF_TOK(TOK_INLINE3, "__inline__") /* gcc extension */
DEF_TOK(TOK_RESTRICT1, "restrict")
DEF_TOK(TOK_RESTRICT2, "__restrict")
DEF_TOK(TOK_RESTRICT3, "__restrict__")
DEF_TOK(TOK_EXTENSION, "__extension__") /* gcc extension */
DEF_TOK(TOK_FLOAT, "float")
DEF_TOK(TOK_DOUBLE, "double")
DEF_TOK(TOK_BOOL, "_Bool")
DEF_TOK(TOK_COMPLEX, "_Complex")
DEF_TOK(TOK_IMAGINARY, "_Imaginary")
DEF_TOK(TOK_SHORT, "short")
DEF_TOK(TOK_STRUCT, "struct")
DEF_TOK(TOK_UNION, "union")
DEF_TOK(TOK_ENUM, "enum")
DEF_TOK(TOK_STATIC, "static")
DEF_TOK(TOK_EXTERN, "extern")
DEF_TOK(TOK_TYPEDEF, "typedef")
DEF_TOK(TOK_SIZEOF, "sizeof")
DEF_TOK(TOK_TYPEOF1, "typeof")
DEF_TOK(TOK_TYPEOF2, "__typeof")
DEF_TOK(TOK_TYPEOF3, "__typeof__")
DEF_TOK(TOK_ATTRIBUTE1, "__attribute")
DEF_TOK(TOK_ATTRIBUTE2, "__attribute__")
DEF_TOK(TOK_ALIGNOF1, "__alignof")
DEF_TOK(TOK_ALIGNOF2, "__alignof__")
DEF_TOK(TOK_ALIGNOF3, "_Alignof")
DEF_TOK(TOK_LABEL, "__label__")
DEF_TOK(TOK_ASM1, "asm")
DEF_TOK(TOK_ASM2, "__asm")
DEF_TOK(TOK_ASM3, "__asm__")

/* Rejestry x86 (niezbędne dla asemblera inline) */
DEF_ASM(al)
DEF_ASM(cl)
DEF_ASM(dl)
DEF_ASM(bl)
DEF_ASM(ah)
DEF_ASM(ch)
DEF_ASM(dh)
DEF_ASM(bh)
DEF_ASM(ax)
DEF_ASM(cx)
DEF_ASM(dx)
DEF_ASM(bx)
DEF_ASM(sp)
DEF_ASM(bp)
DEF_ASM(si)
DEF_ASM(di)
DEF_ASM(eax)
DEF_ASM(ecx)
DEF_ASM(edx)
DEF_ASM(ebx)
DEF_ASM(esp)
DEF_ASM(ebp)
DEF_ASM(esi)
DEF_ASM(edi)
DEF_ASM(rax)
DEF_ASM(rcx)
DEF_ASM(rdx)
DEF_ASM(rbx)
DEF_ASM(rsp)
DEF_ASM(rbp)
DEF_ASM(rsi)
DEF_ASM(rdi)
DEF_ASM(r8)
DEF_ASM(r9)
DEF_ASM(r10)
DEF_ASM(r11)
DEF_ASM(r12)
DEF_ASM(r13)
DEF_ASM(r14)
DEF_ASM(r15)
DEF_ASM(rip)

/* Builtins i Atomici */
DEF_TOK(TOK_builtin_types_compatible_p, "__builtin_types_compatible_p")
DEF_TOK(TOK_builtin_choose_expr, "__builtin_choose_expr")
DEF_TOK(TOK_builtin_constant_p, "__builtin_constant_p")
DEF_TOK(TOK_builtin_frame_address, "__builtin_frame_address")
DEF_TOK(TOK_builtin_return_address, "__builtin_return_address")
DEF_TOK(TOK_builtin_expect, "__builtin_expect")
DEF_TOK(TOK_builtin_unreachable, "__builtin_unreachable")
DEF_TOK(TOK_builtin_va_arg_types, "__builtin_va_arg_types")
DEF_TOK(TOK__Atomic, "_Atomic")
DEF_TOK(TOK_GENERIC, "_Generic")
DEF_TOK(TOK_STATIC_ASSERT, "_Static_assert")
DEF_TOK(TOK_THREAD_LOCAL, "_Thread_local")

/* Funkcje specjalne używane przez generator kodu */
DEF_TOK(TOK_alloca, "alloca")
DEF_TOK(TOK_memset, "memset")
DEF_TOK(TOK_memcpy, "memcpy")
DEF_TOK(TOK_memmove, "memmove")
DEF_TOK(TOK___divdi3, "__divdi3")
DEF_TOK(TOK___moddi3, "__moddi3")
DEF_TOK(TOK___udivdi3, "__udivdi3")
DEF_TOK(TOK___umoddi3, "__umoddi3")