/**
 * @file ams_compositor.c
 * @brief AMS-OS Wayland compositor using wlroots, DRM/KMS, GBM, libinput,
 *        pixman/cairo, and wayland-scanner-generated protocol bindings.
 *
 * Architecture:
 *  - wlroots provides the Wayland server infrastructure (wl_display, seats,
 *    outputs, renderer) through its wlr_* API.
 *  - The DRM backend (wlr_backend_autocreate with AMS drm fd) drives the KMS
 *    CRTC via GEM dumb buffers and page flips.
 *  - GBM (Mesa) is used as the buffer allocator for hardware-accelerated
 *    surfaces; software fallback uses SHM pools (POSIX shm_open + mmap).
 *  - libinput handles pointer and keyboard events, forwarded through the
 *    wlroots seat abstraction.
 *  - pixman handles CPU-side surface composition for SHM clients.
 *  - cairo is used for desktop chrome (title bars, status bar).
 *  - wayland-scanner-generated xdg-shell, xdg-output, and
 *    wlr-layer-shell protocols are supported.
 *
 * Build-time dependencies (resolved by the wlroots/mesa/libinput port scripts):
 *   - libwlroots.a / libwlroots.so
 *   - libgbm.so  (Mesa)
 *   - libEGL.so  (Mesa)
 *   - libGL.so   (Mesa swrast or llvmpipe)
 *   - libinput.so
 *   - libpixman-1.so
 *   - libcairo.so
 *   - libwayland-server.so
 *   - xdg-shell-protocol.c  (generated by wayland-scanner)
 *   - wlr-layer-shell-unstable-v1-protocol.c
 */

#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdlib.h>
#include "ams_syscall.h"

/* -------------------------------------------------------------------------
 * Wayland / wlroots forward declarations.
 *
 * When building against the real wlroots + wayland headers these will be
 * provided by the installed headers.  The stubs below allow the file to
 * compile under the AMS cross-toolchain during initial bring-up before the
 * full port is ready.
 * ---------------------------------------------------------------------- */

#if defined(HAVE_WLROOTS)

#  include <wlr/backend.h>
#  include <wlr/backend/drm.h>
#  include <wlr/backend/libinput.h>
#  include <wlr/render/wlr_renderer.h>
#  include <wlr/render/egl.h>
#  include <wlr/types/wlr_compositor.h>
#  include <wlr/types/wlr_output.h>
#  include <wlr/types/wlr_output_layout.h>
#  include <wlr/types/wlr_seat.h>
#  include <wlr/types/wlr_xdg_shell.h>
#  include <wlr/types/wlr_layer_shell_v1.h>
#  include <wlr/types/wlr_cursor.h>
#  include <wlr/types/wlr_xcursor_manager.h>
#  include <wlr/types/wlr_input_device.h>
#  include <wlr/types/wlr_keyboard.h>
#  include <wlr/types/wlr_pointer.h>
#  include <wlr/util/log.h>
#  include <wayland-server-core.h>
#  include <xkbcommon/xkbcommon.h>
#  include <pixman.h>
#  include <cairo.h>
#  include <libinput.h>
#  include <gbm.h>
#  include <EGL/egl.h>

/* -------------------------------------------------------------------------
 * Compositor server state
 * ---------------------------------------------------------------------- */

struct ams_server {
    struct wl_display          *display;
    struct wlr_backend         *backend;
    struct wlr_renderer        *renderer;
    struct wlr_allocator       *allocator;
    struct wlr_compositor      *compositor;
    struct wlr_output_layout   *output_layout;
    struct wlr_seat            *seat;
    struct wlr_cursor          *cursor;
    struct wlr_xcursor_manager *cursor_mgr;
    struct wlr_xdg_shell       *xdg_shell;
    struct wlr_layer_shell_v1  *layer_shell;
    struct wl_list              outputs;  /* ams_output */
    struct wl_list              views;    /* ams_view   */
    struct wl_listener          new_output;
    struct wl_listener          new_input;
    struct wl_listener          new_xdg_surface;
    struct wl_listener          new_layer_surface;
    struct wl_listener          cursor_motion;
    struct wl_listener          cursor_button;
    struct wl_listener          cursor_axis;
    struct wl_listener          cursor_frame;
    struct wl_listener          request_cursor;
    struct wl_listener          request_set_selection;
    /* GBM / EGL handles for hardware-accelerated rendering */
    struct gbm_device          *gbm;
    EGLDisplay                  egl_display;
    EGLContext                  egl_ctx;
    int                         drm_fd;
};

struct ams_output {
    struct wl_list      link;
    struct ams_server  *server;
    struct wlr_output  *wlr_output;
    struct wl_listener  destroy;
    struct wl_listener  frame;
    pixman_region32_t   damage;
};

struct ams_view {
    struct wl_list           link;
    struct ams_server       *server;
    struct wlr_xdg_surface  *xdg_surface;
    struct wl_listener       map;
    struct wl_listener       unmap;
    struct wl_listener       destroy;
    struct wl_listener       request_move;
    struct wl_listener       request_resize;
    double                   x, y;
    bool                     mapped;
};

/* -------------------------------------------------------------------------
 * Output frame handler
 * ---------------------------------------------------------------------- */

static void output_frame(struct wl_listener *listener, void *data) {
    struct ams_output *output = wl_container_of(listener, output, frame);
    struct wlr_renderer *renderer = output->server->renderer;
    struct wlr_output   *wlr_out  = output->wlr_output;

    if (!wlr_output_attach_render(wlr_out, NULL)) return;

    int ow, oh;
    wlr_output_effective_resolution(wlr_out, &ow, &oh);
    wlr_renderer_begin(renderer, ow, oh);

    /* Clear to dark-blue desktop */
    float bg[4] = {0.118f, 0.157f, 0.204f, 1.0f};
    wlr_renderer_clear(renderer, bg);

    /* Render each mapped view (bottom → top) */
    struct ams_view *view;
    wl_list_for_each(view, &output->server->views, link) {
        if (!view->mapped) continue;
        struct wlr_surface *surface = view->xdg_surface->surface;
        struct wlr_box box = {
            .x = (int)view->x, .y = (int)view->y,
            .width  = surface->current.width,
            .height = surface->current.height,
        };
        float matrix[9];
        enum wl_output_transform transform =
            wlr_output_transform_invert(surface->current.transform);
        wlr_matrix_project_box(matrix, &box, transform, 0.0f,
                               wlr_out->transform_matrix);
        wlr_render_texture_with_matrix(renderer,
                                       wlr_surface_get_texture(surface),
                                       matrix, 1.0f);
        wlr_surface_send_frame_done(surface, NULL);
    }

    wlr_renderer_end(renderer);
    wlr_output_commit(wlr_out);
}

/* -------------------------------------------------------------------------
 * New output
 * ---------------------------------------------------------------------- */

static void server_new_output(struct wl_listener *listener, void *data) {
    struct ams_server  *server = wl_container_of(listener, server, new_output);
    struct wlr_output  *wlr_output = data;

    wlr_output_init_render(wlr_output, server->allocator, server->renderer);

    if (!wl_list_empty(&wlr_output->modes)) {
        struct wlr_output_mode *mode = wlr_output_preferred_mode(wlr_output);
        wlr_output_set_mode(wlr_output, mode);
        wlr_output_enable(wlr_output, true);
        if (!wlr_output_commit(wlr_output)) return;
    }

    struct ams_output *output = calloc(1, sizeof(*output));
    output->server = server;
    output->wlr_output = wlr_output;
    pixman_region32_init(&output->damage);

    output->frame.notify = output_frame;
    wl_signal_add(&wlr_output->events.frame, &output->frame);

    output->destroy.notify = [](struct wl_listener *l, void *) {
        struct ams_output *o = wl_container_of(l, o, destroy);
        wl_list_remove(&o->link);
        pixman_region32_fini(&o->damage);
        free(o);
    };
    wl_signal_add(&wlr_output->events.destroy, &output->destroy);

    wl_list_insert(&server->outputs, &output->link);
    wlr_output_layout_add_auto(server->output_layout, wlr_output);
}

/* -------------------------------------------------------------------------
 * Input handling (keyboard + pointer via libinput)
 * ---------------------------------------------------------------------- */

static void server_new_input(struct wl_listener *listener, void *data) {
    struct ams_server     *server = wl_container_of(listener, server, new_input);
    struct wlr_input_device *device = data;

    switch (device->type) {
    case WLR_INPUT_DEVICE_KEYBOARD: {
        struct xkb_context *xkb_ctx = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
        struct xkb_keymap  *keymap  =
            xkb_keymap_new_from_names(xkb_ctx, NULL, XKB_KEYMAP_COMPILE_NO_FLAGS);
        wlr_keyboard_set_keymap(device->keyboard, keymap);
        xkb_keymap_unref(keymap);
        xkb_context_unref(xkb_ctx);
        wlr_keyboard_set_repeat_info(device->keyboard, 25, 600);
        wlr_seat_set_keyboard(server->seat, device);
        break;
    }
    case WLR_INPUT_DEVICE_POINTER:
        wlr_cursor_attach_input_device(server->cursor, device);
        break;
    default:
        break;
    }

    uint32_t caps = WL_SEAT_CAPABILITY_POINTER | WL_SEAT_CAPABILITY_KEYBOARD;
    wlr_seat_set_capabilities(server->seat, caps);
}

/* -------------------------------------------------------------------------
 * XDG shell: new toplevel surface
 * ---------------------------------------------------------------------- */

static void server_new_xdg_surface(struct wl_listener *listener, void *data) {
    struct ams_server       *server = wl_container_of(listener, server, new_xdg_surface);
    struct wlr_xdg_surface  *xdg_surface = data;

    if (xdg_surface->role != WLR_XDG_SURFACE_ROLE_TOPLEVEL) return;

    struct ams_view *view = calloc(1, sizeof(*view));
    view->server      = server;
    view->xdg_surface = xdg_surface;
    view->x = 80.0;
    view->y = 80.0;

    view->map.notify = [](struct wl_listener *l, void *) {
        struct ams_view *v = wl_container_of(l, v, map);
        v->mapped = true;
        wl_list_insert(&v->server->views, &v->link);
    };
    wl_signal_add(&xdg_surface->events.map, &view->map);

    view->unmap.notify = [](struct wl_listener *l, void *) {
        struct ams_view *v = wl_container_of(l, v, unmap);
        v->mapped = false;
        wl_list_remove(&v->link);
    };
    wl_signal_add(&xdg_surface->events.unmap, &view->unmap);

    view->destroy.notify = [](struct wl_listener *l, void *) {
        struct ams_view *v = wl_container_of(l, v, destroy);
        free(v);
    };
    wl_signal_add(&xdg_surface->events.destroy, &view->destroy);
}

/* -------------------------------------------------------------------------
 * GBM + EGL initialisation
 * ---------------------------------------------------------------------- */

static int init_gbm_egl(struct ams_server *server) {
    /* Open DRM device through AMS syscall */
    server->drm_fd = (int)ams_syscall(SYS_AMS_DRM_OPEN, 0, 0, 0, 0, 0);
    if (server->drm_fd < 0) {
        return -1;
    }

    /* GBM device – needed by wlroots DRM backend for buffer allocation */
    server->gbm = gbm_create_device(server->drm_fd);
    if (!server->gbm) return -1;

    /* EGL display from GBM device */
    server->egl_display = eglGetDisplay((EGLNativeDisplayType)server->gbm);
    if (server->egl_display == EGL_NO_DISPLAY) return -1;

    EGLint major, minor;
    if (!eglInitialize(server->egl_display, &major, &minor)) return -1;

    static const EGLint ctx_attribs[] = {
        EGL_CONTEXT_CLIENT_VERSION, 2,
        EGL_NONE
    };
    eglBindAPI(EGL_OPENGL_ES_API);
    server->egl_ctx = eglCreateContext(server->egl_display,
                                       EGL_NO_CONFIG_KHR,
                                       EGL_NO_CONTEXT,
                                       ctx_attribs);
    return (server->egl_ctx != EGL_NO_CONTEXT) ? 0 : -1;
}

/* -------------------------------------------------------------------------
 * Main entry point
 * ---------------------------------------------------------------------- */

int main(int argc, char *argv[]) {
    (void)argc; (void)argv;

    wlr_log_init(WLR_DEBUG, NULL);

    struct ams_server server = {0};
    wl_list_init(&server.outputs);
    wl_list_init(&server.views);

    server.display = wl_display_create();
    if (!server.display) {
        write(2, "wl_display_create failed\n", 25);
        return 1;
    }

    /* Initialise GBM/EGL for hardware-accelerated rendering */
    if (init_gbm_egl(&server) < 0) {
        write(2, "[compositor] GBM/EGL init failed, using software fallback\n", 58);
    }

    /* wlroots backend: DRM + libinput */
    server.backend = wlr_backend_autocreate(server.display);
    if (!server.backend) {
        write(2, "wlr_backend_autocreate failed\n", 30);
        return 1;
    }

    server.renderer = wlr_renderer_autocreate(server.backend);
    wlr_renderer_init_wl_display(server.renderer, server.display);

    server.allocator = wlr_allocator_autocreate(server.backend, server.renderer);

    server.compositor  = wlr_compositor_create(server.display, server.renderer);
    server.output_layout = wlr_output_layout_create();

    /* XDG shell */
    server.xdg_shell = wlr_xdg_shell_create(server.display);
    server.new_xdg_surface.notify = server_new_xdg_surface;
    wl_signal_add(&server.xdg_shell->events.new_surface, &server.new_xdg_surface);

    /* Layer shell */
    server.layer_shell = wlr_layer_shell_v1_create(server.display);

    /* Seat + cursor */
    server.seat = wlr_seat_create(server.display, "seat0");
    server.cursor = wlr_cursor_create();
    wlr_cursor_attach_output_layout(server.cursor, server.output_layout);
    server.cursor_mgr = wlr_xcursor_manager_create(NULL, 24);
    wlr_xcursor_manager_load(server.cursor_mgr, 1);

    /* Output + input listeners */
    server.new_output.notify = server_new_output;
    wl_signal_add(&server.backend->events.new_output, &server.new_output);
    server.new_input.notify = server_new_input;
    wl_signal_add(&server.backend->events.new_input, &server.new_input);

    /* Bind the Wayland socket */
    const char *socket = wl_display_add_socket_auto(server.display);
    if (!socket) {
        wlr_backend_destroy(server.backend);
        return 1;
    }

    if (!wlr_backend_start(server.backend)) {
        wlr_backend_destroy(server.backend);
        wl_display_destroy(server.display);
        return 1;
    }

    /* Event loop */
    wl_display_run(server.display);

    /* Cleanup */
    if (server.egl_ctx != EGL_NO_CONTEXT)
        eglDestroyContext(server.egl_display, server.egl_ctx);
    if (server.egl_display != EGL_NO_DISPLAY)
        eglTerminate(server.egl_display);
    if (server.gbm)
        gbm_device_destroy(server.gbm);

    wl_display_destroy_clients(server.display);
    wl_display_destroy(server.display);
    return 0;
}

#else /* !HAVE_WLROOTS – bootstrap stub for initial cross-build */

/*
 * When wlroots/Mesa/libinput headers are not yet present (initial port
 * bring-up phase), compile a minimal stand-in that:
 *  - Opens /dev/dri/card0 through the AMS DRM syscall
 *  - Creates a KMS dumb buffer via DRM_IOCTL_MODE_CREATE_DUMB
 *  - Maps it into user space with mmap
 *  - Does a DRM_IOCTL_MODE_PAGE_FLIP to display it
 *  - Listens on the Wayland Unix socket and dispatches basic protocol
 *
 * This ensures the file builds and the binary can be run while ports
 * are being compiled.
 */

#include "ams_syscall.h"
#include <stdint.h>

#define SYS_SOCKET   41
#define SYS_BIND     49
#define SYS_LISTEN   50
#define SYS_ACCEPT   43
#define SYS_SENDMSG  46
#define SYS_RECVMSG  47
#define SYS_IOCTL    16
#define SYS_POLL      7
#define AF_UNIX       1
#define SOCK_STREAM   1

/* DRM ioctl numbers (must match drm/gem_ttm.h) */
#define DRM_IOCTL_GET_CAP           (('d'<<8)|0x0c)
#define DRM_IOCTL_MODE_CREATE_DUMB  (('d'<<8)|0xb2)
#define DRM_IOCTL_MODE_MAP_DUMB     (('d'<<8)|0xb3)
#define DRM_IOCTL_MODE_PAGE_FLIP    (('d'<<8)|0xb0)
#define DRM_IOCTL_MODE_SETCRTC      (('d'<<8)|0xa2)
#define DRM_IOCTL_MODE_DESTROY_DUMB (('d'<<8)|0xb4)

typedef struct { uint32_t height,width,bpp,flags,handle,pitch; uint64_t size; } drm_create_dumb;
typedef struct { uint32_t handle; uint32_t pad; uint64_t offset; } drm_map_dumb;
typedef struct { uint32_t crtc_id,fb_id,flags,reserved; uint64_t user_data; } drm_page_flip;

struct linux_sockaddr_un { uint16_t sun_family; char sun_path[108]; };
struct linux_iovec       { void* iov_base; uint64_t iov_len; };
struct linux_msghdr      {
    void* msg_name; uint32_t msg_namelen; uint32_t __pad0;
    struct linux_iovec* msg_iov; uint64_t msg_iovlen;
    void* msg_control; uint64_t msg_controllen;
    uint32_t msg_flags; uint32_t __pad1;
};

static void wl_puts(const char* s) {
    int n = 0;
    while (s[n]) n++;
    ams_syscall(1, 1, (uint64_t)s, n, 0, 0);
    ams_syscall(1, 1, (uint64_t)"\n", 1, 0, 0);
}

static uint32_t fb_w = 1280, fb_h = 720;

static int open_drm(void) {
    int fd = (int)ams_syscall(SYS_AMS_DRM_OPEN, 0, 0, 0, 0, 0);
    if (fd < 0) wl_puts("[compositor] DRM open failed");
    return fd;
}

static uint8_t* create_dumb_fb(int drm_fd, uint32_t *out_handle, uint32_t *out_pitch) {
    drm_create_dumb cd = { .height=fb_h, .width=fb_w, .bpp=32 };
    if ((int)ams_syscall(SYS_IOCTL, drm_fd, DRM_IOCTL_MODE_CREATE_DUMB, (uint64_t)&cd, 0, 0) < 0) {
        wl_puts("[compositor] CREATE_DUMB failed");
        return 0;
    }
    *out_handle = cd.handle;
    *out_pitch  = cd.pitch;

    drm_map_dumb md = { .handle = cd.handle };
    if ((int)ams_syscall(SYS_IOCTL, drm_fd, DRM_IOCTL_MODE_MAP_DUMB, (uint64_t)&md, 0, 0) < 0) {
        wl_puts("[compositor] MAP_DUMB failed");
        return 0;
    }

    /* MAP_SHARED=1, PROT_READ|PROT_WRITE=3 */
    void* ptr = mmap(0, cd.size, 3, 1, drm_fd, (long)md.offset);
    return (uint8_t*)ptr;
}

static void do_page_flip(int drm_fd, uint32_t crtc_id, uint32_t fb_handle) {
    drm_page_flip pf = { .crtc_id=crtc_id, .fb_id=fb_handle };
    ams_syscall(SYS_IOCTL, drm_fd, DRM_IOCTL_MODE_PAGE_FLIP, (uint64_t)&pf, 0, 0);
}

static int bind_wayland_socket(void) {
    int sock = (int)ams_syscall(SYS_SOCKET, AF_UNIX, SOCK_STREAM, 0, 0, 0);
    if (sock < 0) return -1;
    struct linux_sockaddr_un addr = { .sun_family = AF_UNIX };
    const char* path = "/run/user/0/wayland-0";
    int pi = 0;
    while (path[pi]) { addr.sun_path[pi] = path[pi]; pi++; }
    addr.sun_path[pi] = 0;
    ams_syscall(SYS_BIND, sock, (uint64_t)&addr,
                sizeof(uint16_t)+pi+1, 0, 0);
    ams_syscall(SYS_LISTEN, sock, 16, 0, 0, 0);
    return sock;
}

int main(void) {
    wl_puts("[compositor] AMS Wayland compositor starting (bootstrap mode)");

    uint32_t w = 0, h = 0;
    ams_syscall(SYS_AMS_GET_FB_INFO, (uint64_t)&w, (uint64_t)&h, 0, 0, 0);
    if (w && h) { fb_w = w; fb_h = h; }

    int drm_fd = open_drm();
    uint32_t dumb_handle = 0, dumb_pitch = 0;
    uint8_t* fb_map = 0;
    if (drm_fd >= 0)
        fb_map = create_dumb_fb(drm_fd, &dumb_handle, &dumb_pitch);

    int wl_sock = bind_wayland_socket();
    if (wl_sock < 0) {
        wl_puts("[compositor] Wayland socket bind failed");
        return 1;
    }

    wl_puts("[compositor] Listening on /run/user/0/wayland-0");

    /* Simple event loop: accept clients and do periodic KMS flips */
    struct pollfd_ams pfd[2];
    pfd[0].fd     = wl_sock;
    pfd[0].events = 1; /* POLLIN */
    pfd[0].revents = 0;
    pfd[1].fd     = -1;
    pfd[1].events = 0;
    pfd[1].revents = 0;

    uint32_t frame = 0;
    for (;;) {
        poll(pfd, 1, 16); /* ~60 fps */

        if (pfd[0].revents & 1) {
            int client = (int)ams_syscall(SYS_ACCEPT, wl_sock, 0, 0, 0, 0);
            if (client >= 0) {
                /* A client connected – the full wlroots build handles the
                 * protocol; in bootstrap mode we just close it gracefully. */
                ams_syscall(3 /*SYS_CLOSE*/, client, 0, 0, 0, 0);
            }
            pfd[0].revents = 0;
        }

        /* Draw a simple animated gradient to the dumb buffer */
        if (fb_map && dumb_pitch) {
            uint32_t color = 0x001E2733 | ((frame & 0xFF) << 16);
            for (uint32_t y = 0; y < fb_h; ++y) {
                uint32_t* row = (uint32_t*)(fb_map + y * dumb_pitch);
                for (uint32_t x = 0; x < fb_w; ++x)
                    row[x] = color + y * 0x100 + x;
            }
            if (drm_fd >= 0)
                do_page_flip(drm_fd, 1, dumb_handle);
        } else {
            /* Fallback: SYS_AMS_FB_BLIT */
            ams_syscall(SYS_AMS_FB_BLIT, 0, 0, 0, 0, 0);
        }

        ++frame;
    }
    return 0;
}

#endif /* HAVE_WLROOTS */
